#name: Jinzhu Li
#ONE Card number:1461696
#Computing Science UNIX ID: jinzhu
#lecture section: A2
#lab section: D01
#TA's name: Chenyang Huang

CFLAGS = -Wall -std=c99

draw1b : draw1b.o
	gcc $(CFLAGES) -o draw1b draw1b.o -lm

draw1b.o : draw1b.c
	gcc $(CFLAGES) -c draw1b.c -g

clean : 
	-rm -f *.o draw1b core

